// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzLVmm09D_uCd0XOexP34OqjCAyICPoNI',
    appId: '1:116049642276:web:9eaa6095efec3f5c4329b1',
    messagingSenderId: '116049642276',
    projectId: 'app-perfumes-c0604',
    authDomain: 'app-perfumes-c0604.firebaseapp.com',
    storageBucket: 'app-perfumes-c0604.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMl0Ybd9Q1ARlq4237AtFo46Ql8EiZvKM',
    appId: '1:116049642276:android:26f89ef95ef3bba44329b1',
    messagingSenderId: '116049642276',
    projectId: 'app-perfumes-c0604',
    storageBucket: 'app-perfumes-c0604.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn0lWybSUqcOyN0rpERa6aJL7d-mEva54',
    appId: '1:116049642276:ios:0f64902e5eb5b5cb4329b1',
    messagingSenderId: '116049642276',
    projectId: 'app-perfumes-c0604',
    storageBucket: 'app-perfumes-c0604.firebasestorage.app',
    iosClientId:
        '116049642276-37490nnpsmj2kdl3q9tk5fiokpg8m4t8.apps.googleusercontent.com',
    iosBundleId: 'com.example.primerParcial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn0lWybSUqcOyN0rpERa6aJL7d-mEva54',
    appId: '1:116049642276:ios:0f64902e5eb5b5cb4329b1',
    messagingSenderId: '116049642276',
    projectId: 'app-perfumes-c0604',
    storageBucket: 'app-perfumes-c0604.firebasestorage.app',
    iosClientId:
        '116049642276-37490nnpsmj2kdl3q9tk5fiokpg8m4t8.apps.googleusercontent.com',
    iosBundleId: 'com.example.primerParcial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzLVmm09D_uCd0XOexP34OqjCAyICPoNI',
    appId: '1:116049642276:web:eaf9b20af58734e74329b1',
    messagingSenderId: '116049642276',
    projectId: 'app-perfumes-c0604',
    authDomain: 'app-perfumes-c0604.firebaseapp.com',
    storageBucket: 'app-perfumes-c0604.firebasestorage.app',
  );
}
